# Generated by Django 2.1 on 2018-11-13 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expeditionreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='ファイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日')),
            ],
        ),
    ]
