# Generated by Django 2.1 on 2018-11-09 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainingnote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='コーチ', max_length=30, verbose_name='コメント者')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('trainingnote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingnote.TrainingNote', verbose_name='紐づく投稿')),
            ],
        ),
    ]
